import '@/styles/globals.css'
import NavBar from './NavBar'
import { MoralisProvider } from 'react-moralis'
import Head from 'next/head'
import Footer from './Footer'

export default function App({ Component, pageProps }) {
  return (
    <MoralisProvider initializeOnMount={false}>
        <Head>
          <title>Finance app</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <NavBar/>
          <div style={{padding:"5px 60px 1px 60px"}}>
            <Component {...pageProps} />
            {/* <Footer/> */}
          </div>
          
        </div>

    </MoralisProvider>
    
  
  )
}
